# frozen_string_literal: true

PLATFORM_ALL = -1
PLATFORM_XBOX = 1
PLATFORM_PSN = 2
PLATFORM_STEAM = 3
PLATFORM_EPIC = 6

COMPONENT_TYPE_PROFILES = 'Profiles'.freeze
COMPONENT_TYPE_PROFILE_INVENTORIES = 'ProfileInventories'.freeze
COMPONENT_TYPE_CHARACTERS = 'Characters'.freeze
COMPONENT_TYPE_CHARACTER_INVENTORIES = 'CharacterInventories'.freeze
