# frozen_string_literal: true

PLATFORM_ALL = -1
PLATFORM_XBOX = 1
PLATFORM_PSN = 2
PLATFORM_STEAM = 3
PLATFORM_EPIC = 6

COMPONENT_TYPE_PROFILES = "Profiles"
COMPONENT_TYPE_PROFILE_INVENTORIES = "ProfileInventories"
COMPONENT_TYPE_CHARACTERS = "Characters"
COMPONENT_TYPE_CHARACTER_INVENTORIES = "CharacterInventories"
