# frozen_string_literal: true

PLATFORM_ALL = -1
PLATFORM_XBOX = 1
PLATFORM_PSN = 2
PLATFORM_STEAM = 3

COMPONENT_TYPE_NONE = 0
COMPONENT_TYPE_PROFILES = 100
COMPONENT_TYPE_PROFILE_INVENTORIES = 101
COMPONENT_TYPE_CHARACTERS = 200
COMPONENT_TYPE_CHARACTER_INVENTORIES = 201
